### ISSUE TITLE
Problem with the new update

### ISSUE THREAD

**Issue by HindAlmerekhi** [AdrienGuille/SONDY#2]
Hello,

I've been using SONDY since it's initial release and I absolutely love it. However, with the new update, I wasn't able to use it!

Here is the problem: the event detection algorithms in the new release do not detect events anymore. This is particularly evident when I used an Arabic corpus. I have an old stand alone version of SONDY and it is able to detect events from Arabic tweets. So I believe there is a problem with the new one.

The second issue is that after the new UI update, SONDY is no longer usable. I tried to select my dataset from the interface but the drop down list does not work. This problem was not visible in the previous release.

I would really appreciate it if those issues could be fixed.

Please let me know if you need sample Arabic data to test the event detection algorithms. I have plenty of tweets to share.

**Comment by AdrienGuille** [comment]
Hi,

Thanks for your interest in SONDY :)

Could you be more specific about the versions of SONDY you're referring to?
Please note that the 1.x series and 0.x series rely on different data structures, thus datasets created in SONDY 0.x aren't usable in SONDY 1.0.

If you could share some arabic data with me, it would help me debug the application!

Adrien

**Comment by HindAlmerekhi** [comment]
Hello,

Thank you very much for your prompt reply!

The version that has issues is the latest version (SONDY-1.0-alpha2). And the version that was working fine with me was the version SONDY-1.0-alpha not the 0.x.

Please find the CSV file that contains sample Arabic tweets herehttps://www.dropbox.com/s/mhrqs3ks0kq54ak/ArabicTweets.csv?dl=0. The file contains about 434689 tweets.  I tried to include a large number of tweets to make it comprehensive.

I formatted them to be used as input to SONDY to save you time.

Regards,

Hind Almerekhi

**Comment by AdrienGuille** [comment]
Alright, I've downloaded the data and will test SONDY with them.

Up until the 1.0-alpha release, I was the only developer. The 1-0-alpha2 release includes modifications done by an intern which I have to double-check. I've removed alpha2 for now; if the first alpha version (renamed alpha1) was working fine for you, I guess you can stick with it until alpha2 is fixed. You can re-download it from here: http://mediamining.univ-lyon2.fr/people/guille/sondy.php#app

In case you spot any other problem, don't hesitate to report it! Thank you for helping improving SONDY :)

Adrien

**Comment by fghamsary** [comment]
Hello there @HindAlmerekhi,
This is the so called _intern_ who worked on the SONDY application.
I wonder if you can be a little more precise what doesn't work exactly, because I used Arabic text as well on the application (which I've changed a little of course).
But I can't seem to have a problem with some of the algorithms. As the way the data are stocked have been changed in the last commit, certain algorithms are not compatible. But PeakyTopics, PersistentConversations works completely fine.

By the way the format of the date is not correct on your sample data. I'm trying to load your data to see if I can help you on debugging it.

**Comment by fghamsary** [comment]
@HindAlmerekhi I've reformatted your dates and checked your dataset.
The distribution of your dataset is not a good one. As most of your data is for April 2015, you have some data from February 2012 and your maximum date is December 2015 (how?).
So a good slicing for the time is not possible as well. So If you just consider the part of data that corresponds to the April of 2015, I'm sure that you can find some interesting stuff. I'll do it and will let you know.

**Comment by HindAlmerekhi** [comment]
Sorry about the dataset. I did not notice that the date format was off. Of course there is no data for December 2015 (this is a mistake!).

So is it possible to use SONDY on my data if it was from a single month only (e.g. April 2015)? Or it will not work?

Also, I still have a problem with the UI. I cannot select the dataset from the top right drop down list. For some reason it doesn't seem to work for me. Does it work for you? If so then maybe I have an issue with my machine!

**Comment by HindAlmerekhi** [comment]
Okay I fixed my dataset and apparently there was an issue with my machine. There is no problem with the UI so please ignore my previous issue.

Sorry for the trouble!

I'm still trying to run the remaining algorithms on Arabic data. As you mentioned before that the last commit caused some algorithms to be incompatible. Is it possible to fix them and make them work with Arabic data like English data? In particular, I'm interested in running EDcoW, ET, and MABED algorithms on my data.

**Comment by fghamsary** [comment]
Well as I told you because of the changes of data structure in the last version, some codes should be rewritten.
It is possible to resolve them, but there is constraint of time, maybe @AdrienGuille would be able to help you.
Cheers

**Comment by HindAlmerekhi** [comment]
@fghamsary Thank you for your help so far. Really appreciate it.
@AdrienGuille It would be great if you could fix the algorithms that were changed from the previous release!
