### ISSUE TITLE
Unable to access jarfile SONDY.jar

### ISSUE THREAD

**Issue by JeremyBournay** [AdrienGuille/SONDY#4]
Hi, 
after lunching the project by clicking on autostart.bat, I got a message on the command prompt saying : 
Unable to access jarfile SONDY.jar
 Thank you for helping me with this issues
Regards

**Comment by AdrienGuille** [comment]
Hi Jeremy,

What's your operating system?
Could you download the latest release (https://github.com/AdrienGuille/SONDY/releases) and try it on your system (either by double-clicking on the autostart.bat if you're on Windows, or by running ./autostart.sh in the terminal on UNIX)?
I was able to run this release on Windows 7 and Mac OS X 10.11.

Thank you for your feedback.

Adrien

**Comment by magdambb** [comment]
Hi,
I used that last release instead of the first one that I found github: https://github.com/AdrienGuille/SONDY. It finally worked. Thank you again.

Regards

Groupwork Jeremy and Magda

**Comment by JeremyBournay** [comment]
Hi,

first of all, thank you for your fast feed back. I just want to mention that I'm a french student at Lyon2 (Bron) so we can talk in our native language if doesn't bother you.

My OS is Windows 8.1. I followed all the steps mentionned on github but still doesn't work. I searched the file but I couldn't find it anywhere.

Regards

 

 

 

 

> Message du 24/10/16 16:55
> De : "Adrien Guille" 
> A : "AdrienGuille/SONDY" 
> Copie à : "JeremyBournay" , "Author" 
> Objet : Re: [AdrienGuille/SONDY] Unable to access jarfile SONDY.jar (#4)
> 
>
> Hi Jeremy,

> What's your operating system?
> Could you download the latest release (https://github.com/AdrienGuille/SONDY/releases) and try it on your system (either by double-clicking on the autostart.bat if you're on Windows, or by running ./autostart.sh in the terminal on UNIX)?
> I was able to run this release on Windows 7 and Mac OS X 10.11.

> Thank you for your feedback.

> Adrien

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AdrienGuille/SONDY","title":"AdrienGuille/SONDY","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AdrienGuille/SONDY"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AdrienGuille in #4: Hi Jeremy,\r\n\r\nWhat's your operating system?\r\nCould you download the latest release (https://github.com/AdrienGuille/SONDY/releases) and try it on your system (either by double-clicking on the autostart.bat if you're on Windows, or by running ./autostart.sh in the terminal on UNIX)?\r\nI was able to run this release on Windows 7 and Mac OS X 10.11.\r\n\r\nThank you for your feedback.\r\n\r\nAdrien"}],"action":{"name":"View Issue","url":"https://github.com/AdrienGuille/SONDY/issues/4#issuecomment-255764189"}}}
